### ISSUE TITLE
Realtime_mirroring.git no longer exist.

### ISSUE THREAD

**Issue by octaviawfx** [meareghm/Real-Time-Facial-Mirroring#1]
Thanks for awesome contribution!!!
I installed ros system, and download this project, but found "https://github.com/hansonrobotics/Realtime_mirroring.git " no longer exist, or this project used to be named as "Realtime_mirroring.git"?

I got an error when catkin_make:

####
CMake Error at CMakeLists.txt:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake".

-- Configuring incomplete, errors occurred!
Invoking "cmake" failed.

**Comment by meareghm** [comment]
Hello! Sorry for the invalid URL - I updated the README.md 
The correct git link is: " https://github.com/meareg88/Real-Time-Facial-Mirroring.git "
